Test component
ChartIQ/finsemble-fdc3 pull request #13
Opened 2020-10-17 01:40 UTC by WatsonCIQ

Updating the test component styling

Testing Steps: 

1. Run the watch script to add FDC3 and the tester to the seed project
1. Load the tester and confirm the bellow items

- [ ] Tester is in the launcher menu
- [ ] The tester adapts to the change in component size
- [ ] Each FDC3 API is covered
- [ ] Menu appears when clicking on the hamburger icon and takes you to the correct location
Test each API call by confirming the following: 
- [ ] If the API has a clipboard icon it copies an example that can be pasted into the input below it
- [ ] If an API has an input box you can input text and the test will update in real-time in the snippet area below 
- [ ] When the run button is clicked the show code result button is no longer disabled (there are one or two calls that do not return values and will remain disabled) 
- [ ] If the show result button is enabled it should show the returned value/output of code action

**Notes:** 
addIntentListener does not seem to be working correctly (tested in the javascript console too)

2020-10-19 17:59 UTC, NinjaManatee requested changes
Burger menu doesn't work for `open` method. 
Some of the inputs are hard coded (e.g. the context for `open`)
`getCurrentChannel` doesn't display anything if you have left the channel (should display null or undefined).
`findIntent` does not have the option to pass in context.
There are two copies of the same `useEffect` in `ApiExample.jsx`
It isn't clear what should happen for `addContextListener`.

2020-10-19 17:59 UTC, NinjaManatee commented on src/components/FDC3Tester/src/components/ApiExample.jsx
> +  const updateResult = (result) => {
Unused function definition

2020-10-19 17:59 UTC, NinjaManatee commented on src/components/FDC3Tester/src/components/ApiExample.jsx
> +        if (apiName.includes("broadcast") || apiName.includes("findIntentsByContext")) {
Should these be equals instead of includes?

2020-10-19 17:59 UTC, NinjaManatee commented on src/components/FDC3Tester/src/Apps.jsx
> +        title="Open"
The burger menu doesn't work for Open, possibly because of the capitalization here.

2020-10-19 17:59 UTC, NinjaManatee commented on src/components/FDC3Tester/src/Context.jsx
> +        codeAction={(...args) => fdc3.addContextListener(...args)}
It isn't clear to me how to test `addContextListener`. I'm not sure what is supposed to happen when the listener is triggered for these tests. It should print the context to the output panel, but I don't think it does that.

2020-10-19 17:59 UTC, NinjaManatee commented on src/components/FDC3Tester/src/Channels.jsx
> +      <ApiExample
`getCurrentChannel` doesn't display anything after you `leaveCurrentChannel`. It should display some sort of message, or at least `null`.

2020-10-21 16:14 UTC, WatsonCIQ commented
> Burger menu doesn't work for `open` method.
> Some of the inputs are hard coded (e.g. the context for `open`)
> `getCurrentChannel` doesn't display anything if you have left the channel (should display null or undefined).
> `findIntent` does not have the option to pass in context.
> There are two copies of the same `useEffect` in `ApiExample.jsx`
> It isn't clear what should happen for `addContextListener`.

Thanks @NinjaManatee I will get onto these changes today/tomorrow! I always forget how good at code reviews you are 👍 . 
Really good feedback and thanks for the thorough checking!

2020-11-12 02:27 UTC, WatsonCIQ commented
I've fixed the issues locally but have a merge issue and can't seem to resolve to push the changes.
I will try again tomorrow :(

2020-11-12 14:20 UTC, sgd2z commented
@NinjaManatee has fixed most review comments. Merging this now and future changes can be with new PRs.

2020-11-12 14:23 UTC, sgd2z approved these changes

2020-11-12 14:23 UTC, merged